#7 gauge
cyder-akashi/AktivaTurbo pull request #13
Opened 2017-03-13 00:51 UTC by Kousuke-N

円形ゲージの作成

・ゲージの属性を持つattrs.xml
・ゲージの挙動を記述したCircleGauge.java
・アニメーションなどの挙動は未記述
・３つのゲージは作成

2017-03-14 13:37 UTC, mori-atsushi requested changes

2017-03-14 13:37 UTC, mori-atsushi commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:2.3.0'
これはAndroid Studioバージョンアップに伴う変更かな？
別のPull Requestにしておきたいな。

2017-03-14 13:37 UTC, Mori-Atsushi commented on wear/src/main/java/com/example/cyder/aktivaturbo/CircleGauge.java
> +	public CircleGauge(Context context) {
CircleGauge(Context context)とCircleGauge(Context context, AttributeSet attrs, int defStyleAttr)は必要？

2017-03-14 13:37 UTC, Mori-Atsushi commented on wear/src/main/java/com/example/cyder/aktivaturbo/CircleGauge.java
> +package com.example.cyder.aktivaturbo;
commonとかcomponentとかのフォルダに入れたほうがいいかも？

2017-03-14 13:37 UTC, Mori-Atsushi commented on wear/src/main/java/com/example/cyder/aktivaturbo/CircleGauge.java
> +		Resources res = getResources();
このres使ってなくない？

2017-03-14 13:37 UTC, Mori-Atsushi commented on wear/src/main/java/com/example/cyder/aktivaturbo/CircleGauge.java
> +	private int gaugeRadius = 100;
今回は別に端末が固定だから構わないだろうけど、実際は端末の横幅に合わせて可変のほうが好ましい？

2017-03-14 13:37 UTC, Mori-Atsushi commented on wear/src/main/java/com/example/cyder/aktivaturbo/CircleGauge.java
> +//		(3)
(4)で隠れちゃうから(3)いらないかも？

2017-03-14 13:41 UTC, Mori-Atsushi commented
簡単に直せるとこ、重要なとこだけ直しちゃってマージしましょう。

2017-03-14 13:42 UTC, Kousuke-N commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:2.3.0'
おそらく…
少なくとも手動で変えたものではないですね…

2017-03-14 13:43 UTC, Kousuke-N commented on wear/src/main/java/com/example/cyder/aktivaturbo/CircleGauge.java
> +package com.example.cyder.aktivaturbo;
あーjavaのフォルダじゃなくってっていうことですかね？
そういうのって何か問題が発生したりしないのかな…
まあちょっとやってみます

2017-03-14 13:43 UTC, Mori-Atsushi commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:2.3.0'
同じようにバージョンアップに伴う記述がいくつかあるので、
できれば分けてマージしたいよね。
今回はまぁ、どちらでもいいけど…

2017-03-14 13:44 UTC, Mori-Atsushi commented on wear/src/main/java/com/example/cyder/aktivaturbo/CircleGauge.java
> +package com.example.cyder.aktivaturbo;
```
wear/src/main/java/com/example/cyder/aktivaturbo/common/CircleGauge.java
```
とかのイメージ

2017-03-14 13:44 UTC, Kousuke-N commented on wear/src/main/java/com/example/cyder/aktivaturbo/CircleGauge.java
> +	private int gaugeRadius = 100;
それを言うならそもそも四角形の端末にしか対応しないようにしたのでいろいろと変更はしないといけないっぽいですね

2017-03-14 13:45 UTC, Kousuke-N commented on wear/src/main/java/com/example/cyder/aktivaturbo/CircleGauge.java
> +	public CircleGauge(Context context) {
う～んなにせweb読みながらやったので…
でもたぶんいらない気もします

2017-03-15 13:59 UTC, Kousuke-N reviewed
簡単なとこは直しました。
レビューお願いします

2017-03-15 13:59 UTC, Kousuke-N commented on wear/src/main/java/com/example/cyder/aktivaturbo/CircleGauge.java
> +		Resources res = getResources();
あー使ってないですね…
削除しておきます

2017-03-15 13:59 UTC, Kousuke-N commented on wear/src/main/java/com/example/cyder/aktivaturbo/CircleGauge.java
> +//		(3)
あ、確かにそうですね
了解です

2017-03-15 13:59 UTC, Kousuke-N commented on wear/src/main/java/com/example/cyder/aktivaturbo/CircleGauge.java
> +	public CircleGauge(Context context) {
削除しました

2017-03-15 13:59 UTC, Kousuke-N commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:2.3.0'
今回はスル―します

2017-03-15 13:59 UTC, Kousuke-N commented on wear/src/main/java/com/example/cyder/aktivaturbo/CircleGauge.java
> +package com.example.cyder.aktivaturbo;
ちょっとやってみようとしましたがめんどくさそうなのでスル―します

2017-03-15 13:59 UTC, Kousuke-N commented on wear/src/main/java/com/example/cyder/aktivaturbo/CircleGauge.java
> +		Resources res = getResources();
削除しました

2017-03-15 13:59 UTC, Kousuke-N commented on wear/src/main/java/com/example/cyder/aktivaturbo/CircleGauge.java
> +//		(3)
削除しました

2017-03-16 00:31 UTC, mori-atsushi requested changes

2017-03-16 00:31 UTC, Mori-Atsushi commented on wear/src/main/java/com/example/cyder/aktivaturbo/MainActivity.java
> +	private RelativeLayout relativeLayout;
インデントおかしくないですか？

2017-03-16 00:44 UTC, Mori-Atsushi commented on wear/src/main/java/com/example/cyder/aktivaturbo/MainActivity.java
> +	private RelativeLayout relativeLayout;
全体的にタブインデントなのか、スペースインデントなのかはっきりさせよう。

2017-03-16 03:43 UTC, Kousuke-N commented on wear/src/main/java/com/example/cyder/aktivaturbo/MainActivity.java
> +	private RelativeLayout relativeLayout;
スペースインデントに統一しました

2017-03-16 03:55 UTC, mori-atsushi approved these changes
コミットを整理してからマージしましょう！

2017-03-16 05:54 UTC, merged