仕様書を作成 #1
cyder-akashi/AktivaTurbo pull request #5
Opened 2017-02-24 16:02 UTC by Mori-Atsushi

#1  仕様書を作成しました。

2017-02-25 14:21 UTC, Nishihara-Daiki requested changes
Sectionの文字が見にくいので、そこだけちょっと工夫したい？

2017-02-25 14:26 UTC, Kousuke-N commented
リスタート画面がちょっとださいような気が…

2017-02-25 14:27 UTC, Kousuke-N commented
ゲージがマックスになったとき文字が見えなくなるのでは

2017-02-25 14:28 UTC, mori-atsushi reviewed
テスト投稿

2017-02-25 14:29 UTC, Kousuke-N reviewed
リスタート画面がちょっとださい気が…

2017-02-25 14:30 UTC, Kousuke-N reviewed
ゲージがマックスになったときに文字が消えてしまうのでは？

2017-02-25 17:15 UTC, e45395 commented
文字色→白(#efefef)
リスタート画面の背景色の黒色をもう少し黒くする。

2017-03-01 08:16 UTC, Nishihara-Daiki approved these changes

2017-03-01 12:02 UTC, merged